spring:
  # for sql
  datasource:
    url: jdbc:mysql://119.91.61.248:3306/xiaoxi_daily
    username: shiyixi
    password: '@SY315131x666'
    driver-class-name: com.mysql.cj.jdbc.Driver
  # for redis
  redis:
    host: 119.91.61.248
    port: 6379
    password: '@SY315131x666'
  cache:
    redis:
      # 缓存过期时间
      time-to-live: 1800000

# for mybatis-plus
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8081
